name: CI Backend

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar Poetry
        run: pip install poetry

      - name: Instalar dependencias
        run: poetry install --no-interaction --no-ansi

      - name: Rodar testes com Pytest
        run: poetry run pytest -v
